version: '3.2'
services: 
  sqlserver:
    container_name: sqlserver
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "2021@Challenge!Jobsity"
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    networks:
      - chat.network
    ports: 
      - "1433:1433"
    restart: on-failure
    volumes:
      - ./volumes/mssql/data:/var/opt/mssql/data
      - ./volumes/mssql/logs:/var/opt/mssql/log
      - ./volumes/mssql/secrets:/var/opt/mssql/secrets

  rabbit:
    hostname: rabbit
    container_name: rabbit
    image: rabbitmq:management-alpine
    environment: 
      RABBITMQ_DEFAULT_USER: chatbot
      RABBITMQ_DEFAULT_PASS: chatbot1337
    networks: 
      - chat.network
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: on-failure
    volumes: 
      - ./volumes/rabbit:/var/lib/rabbitmq/mnesia

  chat:
    build:
      context: .
      dockerfile: Dockerfile.chat
    container_name: chat
    depends_on: 
      - rabbit
    environment: 
      - DBDATABASE=ChatDB
      - DBHOST=sqlserver
      - DBPASSWORD=2021@Challenge!Jobsity
      - DBPORT=1433
      - DBUSER=sa
      - ENGINE=mssql
      - RabbitMQConnection=amqp://chatbot:chatbot1337@rabbit:5672
    links: 
      - sqlserver
      - rabbit
    networks:
      - chat.network
    ports: 
      - "4000:80"
    restart: on-failure
      
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: bot
    depends_on: 
      - rabbit
    environment: 
      - RabbitMQConnection=amqp://chatbot:chatbot1337@rabbit:5672
    links: 
      - rabbit
    networks:
      - chat.network
    restart: on-failure
networks: 
  chat.network: